# Generated by Django 5.2.5 on 2025-08-25 02:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PropertyInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=500)),
                (
                    "lot_size",
                    models.DecimalField(
                        decimal_places=2, help_text="Lot size value", max_digits=10
                    ),
                ),
                (
                    "lot_size_unit",
                    models.CharField(
                        choices=[("acres", "Acres"), ("hectares", "Hectares")],
                        default="acres",
                        help_text="Unit for lot size",
                        max_length=10,
                    ),
                ),
                (
                    "current_property",
                    models.TextField(help_text="Current property description"),
                ),
                (
                    "property_goals",
                    models.TextField(help_text="Property goals and objectives"),
                ),
                (
                    "investment_capacity",
                    models.TextField(help_text="Investment capacity and timeline"),
                ),
                (
                    "preferences_concerns",
                    models.TextField(help_text="Preferences and concerns"),
                ),
                (
                    "region",
                    models.CharField(help_text="Geographic region", max_length=100),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "Property Inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=200)),
                ("project_description", models.TextField()),
                (
                    "confidence_score",
                    models.FloatField(help_text="AI confidence score (0.0 to 1.0)"),
                ),
                (
                    "factors_considered",
                    models.JSONField(help_text="Factors considered in the estimate"),
                ),
                (
                    "recommendations",
                    models.JSONField(help_text="AI recommendations for the project"),
                ),
                (
                    "timeline",
                    models.CharField(
                        help_text="Recommended project timeline", max_length=200
                    ),
                ),
                (
                    "risk_assessment",
                    models.TextField(
                        help_text="Risk assessment and mitigation strategies"
                    ),
                ),
                (
                    "cash_flow_projection",
                    models.JSONField(
                        default=list,
                        help_text="10-year net cash flow projection in USD",
                    ),
                ),
                (
                    "revenue_breakdown",
                    models.JSONField(
                        default=dict, help_text="10-year revenue breakdown by category"
                    ),
                ),
                (
                    "cost_breakdown",
                    models.JSONField(
                        default=dict, help_text="10-year cost breakdown by category"
                    ),
                ),
                ("ai_response_raw", models.JSONField(help_text="Raw AI response data")),
                (
                    "processing_time",
                    models.FloatField(help_text="Processing time in seconds"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "inquiry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimate",
                        to="main_app.propertyinquiry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Property Estimates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIAnalysisLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_data", models.JSONField(help_text="Request data sent to AI")),
                ("response_data", models.JSONField(help_text="Response data from AI")),
                (
                    "model_used",
                    models.CharField(help_text="AI model used", max_length=100),
                ),
                ("tokens_used", models.IntegerField(help_text="Tokens consumed")),
                (
                    "processing_time",
                    models.FloatField(help_text="Processing time in seconds"),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, help_text="Whether the analysis was successful"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if analysis failed"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_logs",
                        to="main_app.propertyinquiry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "AI Analysis Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
